/**
 * Stable, public error codes returned in the `code` field of every error
 * response. These are part of the API contract - do not rename without a
 * version bump. See docs/security.md for the full status-code mapping.
 */
export enum ErrorCode {
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_NOT_CONFIRMED = 'EMAIL_NOT_CONFIRMED',
  USERNAME_TAKEN = 'USERNAME_TAKEN',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  PROFILE_SETUP_REQUIRED = 'PROFILE_SETUP_REQUIRED',
  USERNAME_INVALID = 'USERNAME_INVALID',
  BIRTH_DATE_INVALID = 'BIRTH_DATE_INVALID',
  AGE_REQUIREMENT_NOT_MET = 'AGE_REQUIREMENT_NOT_MET',
  PROFILE_VALIDATION_ERROR = 'PROFILE_VALIDATION_ERROR',
  AVATAR_INVALID = 'AVATAR_INVALID',
  AVATAR_TOO_LARGE = 'AVATAR_TOO_LARGE',
  LEISURE_ITEM_NOT_FOUND = 'LEISURE_ITEM_NOT_FOUND',
  LEISURE_ITEM_DETAILS_INVALID = 'LEISURE_ITEM_DETAILS_INVALID',
  LEISURE_PLAN_ENTRY_NOT_FOUND = 'LEISURE_PLAN_ENTRY_NOT_FOUND',
  LEISURE_PLAN_ENTRY_DATE_INVALID = 'LEISURE_PLAN_ENTRY_DATE_INVALID',
  LEISURE_NOTE_NOT_FOUND = 'LEISURE_NOTE_NOT_FOUND',
  LEISURE_COLLECTION_NOT_FOUND = 'LEISURE_COLLECTION_NOT_FOUND',
}
